#!/usr/bin/python
import sys
#scrypt password plaintext ciphertext

if(len(sys.argv) == 4):
    password = sys.argv[1]
    pfile = sys.argv[2]
    cfile = sys.argv[3]
else:
    print("usage: ./scrypt [-d] password plaintextfile ciphertextfile")
    sys.exit(3)


try:
    with open(pfile) as f:
        plaintext= f.read()
except:
    print("./scrypt: cannot open plaintext file for reading " + '"' + pfile + '"')
    sys.exit(3)

def lcg ():
    a = 1103515245
    c = 12345
    m = 256
    global rand
    rand = (a*rand + c) % m
    return rand

def sdbm(password):
    hash = 0
    for chr in password:
        hash = ord(chr) + (hash << 6) + (hash << 16) - hash
    return hash

encryption = ''
xor = 0
rand = sdbm(password)

print("using seed=" + str(rand) + " from password=" + '"' + password + '"')


for i in range(len(plaintext)):
    xor = lcg() ^ ord(plaintext[i])
    encryption = encryption + chr(xor)

w = open(cfile,"w+")
n = w.write(encryption)
