#!/usr/bin/python
import sys

zerobyte = False
nokeyfile = False

if len(sys.argv)==4:
    kfile = sys.argv[1]
    if(sys.argv[1] == '-k'):
        print("got key but wrong args: optind=3 argc=4")
        print("usage: python vencrypt [keyfile | -k key] plaintextfile ciphertextfile")
        sys.exit(3)
    pfile = sys.argv[2]
    enfile = sys.argv[3]
elif len(sys.argv)==5:
    if(sys.argv[1] != '-k'):
        print("invalid option -" + sys.argv[1])
        sys.exit(3)
    kfile = sys.argv[2]
    pfile = sys.argv[3]
    enfile = sys.argv[4]
    lines = kfile
    nokeyfile = True
else:
    print("usage: python vencrypt [keyfile | -k key] plaintextfile ciphertextfile")
    sys.exit(3)

if nokeyfile == False:
    try:
        with open(kfile) as f:
            lines = f.read()
        if not lines:
            print("empty key file")
            sys.exit(3)
    except:
        print("cannot open key file " + kfile)
        sys.exit(3)

print("keyfile=" + kfile + ", length=" + str(len(lines)))

try:
    with open(pfile) as f:
        plaintext= f.read()
        if not plaintext:
            zerobyte = True
            encryption = ''
except:
    print("./vencrypt: cannot open plaintext file for reading " + '"' + pfile + '"' )
    sys.exit(3)

if(zerobyte == False): 
    i = 0
    j = 1
    encryption = ''
    keylength = len(lines)
    while(i < len(plaintext)):
        hex = ((ord(plaintext[i]) + ord(lines[j - 1])) % 256)
        encryption = encryption + chr(hex)
        i,j = i+ 1, j + 1
        if(j>keylength):j = 1

w = open(enfile,"w+")
n = w.write(encryption)
w.close()